sudo: false
language: node_js
node_js: stable
cache:
  directories:
    - $HOME/.npm
stages:
  - dependencies
  - lint
  - test
jobs:
  include:
    - stage: dependencies
      script: skip
      name: "Update deps cache"
    - stage: lint
      name: "Lint JS"
      script: npm run lint:js
    - script: npm run lint:css
      name: "Lint CSS"
    - script: npm run lint:ec
      name: "Lint by editorconfig"
    - script: npm run lint:webext
      name: "Lint Extension"
    - stage: test
      after_success: npm run coverage
